baseURL = 'https://joshuacharrison.com/'
locale = 'en-us'
title = 'Joshua Harrison'
disableKinds = ['taxonomy', 'term']

[params]
  description = 'The professional resume website of Joshua Harrison.'
